export interface FaqItem {
  question: string;
  answer: string;
}

export const EducatinalFaq: FaqItem[] = [
  {
    question: "DO YOUR STANDARDS MEET WHAT IS REQUIRED FOR AN EDUCATION FACILITY?",
    answer:
    "Excelling in a school or university environment requires more than just a strong curriculum and well-planned timetables—it demands an environment that actively supports focus and development. Over years of hands-on experience, Cleanworks has seen how a immaculate campus directly elevates the mindset of both students and faculty. Being true education cleaning specialists goes far beyond standard custodial work. We maintain a dedicated department of education-focused professionals trained specifically for the unique demands of early learning centers through to university campuses. Our reputation is built on creating flawless spaces where students can focus entirely on their studies without distraction. Business and facility managers often struggle to find a service provider that genuinely takes pride in educational standards. Where others see a basic contract, Cleanworks sees a public health partnership—a commitment shared by many of our team members who are parents themselves. Partnering with vetted contract cleaners who understand high-touch academic environments does more than satisfy daily compliance checks; it protects and enhances your institution’s standing. A neglected library or tired common room can quickly drain energy from a campus. That is why our holistic cleaning solutions are seamlessly integrated into the daily life of every facility we protect.",
  },
  {
    question: "HOW DO YOU PRIORITISE HEALTH AND SAFETY FOR CHILDCARE CENTRES?",
    answer:
    "Childcare centres, daycare facilities, and kindergartens operate under strict health, hygiene, and safety regulations, making professional cleaning an essential part of maintaining compliance with the National Quality Standard (NQS). From busy classrooms and play areas to shared learning spaces, every environment experiences constant activity throughout the day. Maintaining exceptional cleanliness helps create a healthier setting where children can learn, play, and thrive while giving parents confidence that their children are cared for in a safe, hygienic environment.Unlike standard commercial spaces, childcare facilities require specialised cleaning techniques designed specifically for early learning environments. Our trained childcare cleaning professionals understand that the highest-risk areas are often floor mats, play equipment, shared toys, low-level shelving, bathroom facilities, and other high-touch surfaces where germs can spread quickly. Using industry-approved cleaning methods and high-quality disinfectants, we help minimise cross-contamination while supporting a cleaner and healthier environment for children and educators.Choosing the right childcare cleaning provider means partnering with a team that understands the unique demands of early learning centres. Our tailored cleaning schedules, consistent quality standards, and attention to detail ensure every area is thoroughly cleaned and sanitised—from classrooms and nap areas to kitchens, washrooms, and outdoor play zones. Whether you operate a small independent childcare centre or a large multi-site organisation, our experienced team delivers reliable, compliant, and professional cleaning services that help create a welcoming environment where children, staff, and families can feel confident every day.", 
  },
  {
    question: "HOW DO YOU MAINTAIN A STANDARD OF HYGIENE EXCELLENCE FOR SCHOOLS?",
    answer:
    "As children grow, the challenges of maintaining their environment grow with them. From the muddy boots of a primary school playground to the science lab spills of a secondary school  the diversity of mess is impressive, to say the least. This is where the role of our department of education cleaners becomes vital. These institutions are sprawling, often aging buildings that require a keen eye for detail and a robust work ethic. We were found that the best education cleaners are those who respect the heritage of the campus, treating and cleaning the school floors and trophy cabinets with the respect they deserve.Many principals find themselves frustrated with the ghost-like services of the past – teams that show up, do the bare minimum, and vanish. As a highly reputable school cleaning company, we believe in visibility and accountability. Cleanworks focuses on the fact that a clean school is a safe school. When researching cleaners for schools, you need a crew that understands the ebb and flow of the school terms. You need a cleaning company for schools that can handle the deep cleans during the holidays and the rapid-response spills during the athletics carnival.The competitive field of school cleaning companies often leads to a race to the bottom on price, which unfortunately results in a race to the bottom on the quality of output. We, at Cleanworks, refuse to play that game. We position ourselves as the leading cleaning companies for schools because we value our crew, standards and our process. Whether you require contract cleaners for schools for a multi-campus private college or a single contract cleaner for schools for a local primary facility, the impeccably high standards remain. We also pay special attention to the often-overlooked areas, ensuring that education centres bathroom cleaners are using the right chemistry to combat the heavy usage these areas see between recesses and lunch breaks."
  },
  {
    question: "CAN YOUR UNIVERSITY CLEANING REFLECT OUR ACADEMIC HERITAGE?",
    answer:
    "Universities operate around the clock, requiring specialised cleaning solutions that support busy lecture halls, libraries, laboratories, student accommodation, and shared learning spaces. Our professional university cleaning services are tailored to maintain exceptional hygiene, protect valuable facilities, and create a clean, safe, and welcoming environment for students, faculty, researchers, and visitors. With flexible scheduling, industry-approved cleaning practices, and experienced teams, we deliver consistent, high-quality results while minimising disruption to academic activities and helping institutions maintain a professional campus year-round.",
  },
  {
    question: "WHY WOULD I CHOOSE CLEANWORKS FOR OUR EDUCATION FACILITY?",
    answer:
    "Our commitment to educational cleaning goes beyond appearance—we create cleaner, healthier, and safer learning environments where students and educators can thrive. From childcare centres and schools to colleges and universities, our experienced team delivers consistent, high-quality cleaning services tailored to the unique needs of every facility. Using industry-approved methods, flexible scheduling, and meticulous attention to detail, we help educational institutions maintain welcoming spaces that support wellbeing, productivity, and academic success throughout the year.",
  },
];