import {TeamMember,TeamCardProps}  from "../_components/teamCard"
export const teamMembers: TeamMember[] = [
  {
    id: 1,
    name: "Michael Anderson",
    position: "Founder & CEO",
    image: "/images/about/team-1.jpg",
    imageWidth: 400,
    imageHeight: 500,
    email: "michael.a@c1securitycleaning.com",
    linkedin: "https://linkedin.com/in/michael-anderson",
    twitter: "https://x.com/manderson_c1",
    facebook: "https://facebook.com/michael.anderson.c1",
  },
  {
    id: 2,
    name: "Sarah Jenkins",
    position: "Head of Operations",
    image: "/images/about/team-2.jpg",
    imageWidth: 400,
    imageHeight: 500,
    email: "sarah.j@c1securitycleaning.com",
    linkedin: "https://linkedin.com/in/sarah-jenkins",
    twitter: "https://x.com/sjenkins_ops",
  },
  {
    id: 3,
    name: "David Rodriguez",
    position: "Chief Security Officer",
    image: "/images/about/team-3.jpg",
    imageWidth: 400,
    imageHeight: 500,
    email: "david.r@c1securitycleaning.com",
    linkedin: "https://linkedin.com/in/david-rodriguez-sec",
    facebook: "https://facebook.com/david.rodriguez.c1",
  },
  {
    id: 4,
    name: "Emily Chen",
    position: "Commercial Sanitation Director",
    image: "/images/about/team-4.jpg",
    imageWidth: 400,
    imageHeight: 500,
    email: "emily.c@c1securitycleaning.com",
    linkedin: "https://linkedin.com/in/emily-chen-clean",
  },
];