import type { Metadata } from "next";
import { Outfit, Nunito } from "next/font/google";
import "../globals.css";
import "leaflet/dist/leaflet.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Control-1 Security",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="/tac-fav-icon.png"
        type="image/x-icon"
        sizes="16x16 32x32 48x48"
      />
      <body className={`${outfit.variable} ${nunito.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
